name: ag_widgets
description: Enhance your apps with our versatile smart widgets. Designed for daily development projects, they streamline workflows and boost functionality.
version: 0.3.0
#homepage: https://www.ankitgada.in
repository: https://github.com/dev-ankit1207/ag_widgets
issue_tracker: https://github.com/dev-ankit1207/ag_widgets/issues

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter_svg: ^2.0.8
  nb_utils: ^6.0.6
  simple_animations: ^5.0.2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.example.ag_widgets
        pluginClass: AgWidgetsPlugin
      ios:
        pluginClass: AgWidgetsPlugin
      linux:
        pluginClass: AgWidgetsPlugin
      macos:
        pluginClass: AgWidgetsPlugin
      windows:
        pluginClass: AgWidgetsPluginCApi
      web:
        pluginClass: AgWidgetsWeb
        fileName: ag_widgets_web.dart